---
name: Snyk Infrastructure as Code
on:
  push:
    paths:
      - "dist/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for Kubernetes configuration issues 
        uses: snyk/actions/iac@master
        with:
          file: dist/snykit.yaml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: garethr/snyk-to-sarif@master
      - uses: actions/upload-artifact@v2
        with:
          name: SARIF
          path: snyk.sarif
      - uses: actions/upload-artifact@v2
        with:
          name: Snyk JSON output
          path: snyk.json
      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
